### PR TITLE
Improve pipeline balance

### PR DESCRIPTION
**Pull request by benjaminplee**
Our team found that when iBrowse was under significant load (>1k req/sec) that the current implementation of the pipelining algorithm was wreaking havoc with our network-load-balancer.  Load would be correctly sent out, however some connections received a largely disproportionate amount of the load.  This pull request is inspired by the incomplete work done on cmullaparthi/ibrowse@d61dd9a074ac7f9d63445ac9a19670a11aaf9640 , **however** it does not include all of the additional features or possible bug fixes in that branch (without more information testing and verifying of all additional features was too large of a task for my team at the moment).

These changes rework the pipelining algorithm to more effectively balance requests across the sessions based by giving new work to the session with the smallest existing pipeline queue size _(ties broken by last completed request timestamp and pid as a last resort)_.

In addition...
* new eunit based functional tests were added to verify the balancing to the test server and other cases _(may want to move all functional testing to this or similar pattern to reduce manual verification needed when running tests)_
* Updated rebar to 2.5.2 to resolve issue with eunit tests not all being picked up
* Fixed a bug in the test http server related to shut down
* Removed unnecessary tracking of pipeline and session pool sizes; using authoritative sources instead
* Encapsulated connection pool management details to within ibrowse_lb
* Work was done while pair programming; authorship and contributor docs have been updated.

_This pull request replaces pull request #122_

### CODE REVIEW

**Comment by yabrams** [comment]
Hi Chandru and Benjamin,

This pull request is seem to be opened for very long time although it includes some significant improvements (that I also tested by myself and showed great results)
Is there a reason not to pull it to the master?

thanks

**Comment by cmullaparthi** [comment]
Hi,

I really like Benjamin's contribution. The only problem was that the pipelining code had already undergone a lot of changes in the new_pipeline branch and the two had to be merged by hand manually. Its been on my mind for a long time but I'm procrastinating way too much. I will have some free time later this week so I will definitely make an effort to merge the two.

BTW, it would be very useful if you could test your use case with the new_pipeline branch and give any feedback.

**Comment by yabrams** [comment]
I tested it already and it showed significant results
the number of request timeouts decreased dramatically and the servers performance seem to be 3-4 times better than before.
please note that I only tried the new_pipeline branch and without Benjamin's additions.

I'll be waiting for the merge, thanks.

**Comment by cmullaparthi** [comment]
I've done a first pass at merging 'new_pipeline' and this pull request. Result is at https://github.com/cmullaparthi/ibrowse/tree/merge_pull_req_123 

I've yet to run performance tests on this, but all Eunit and functional tests pass.

**Comment by cmullaparthi** [comment]
I've manually merged this into master. All tests pass and some pretty good performance test results as well using httpcbench. I have not taken some of the more radical changes to ibrowse_lb.erl as the changes made to it as part of the work on the new_pipeline branch deliver the required improvements. The improvements made to the testing of ibrowse is very much appreciated indeed. Many thanks for contributing to ibrowse and apologies the for delay in integrating this into master.

```
$ ./run_client ibrowse
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:true]

Eshell V6.4  (abort with ^G)
1> Starting 1000 calls (18.036 MB)
1000: 6240 rt, 3638 ct, 75.575 MB (57.539 increase), 0 failures
2000: 6540 rt, 3749 ct, 78.939 MB (60.903 increase), 0 failures
3000: 6850 rt, 3863 ct, 84.270 MB (66.234 increase), 0 failures
4000: 7150 rt, 3971 ct, 86.234 MB (68.198 increase), 0 failures
5000: 7460 rt, 4087 ct, 84.802 MB (66.766 increase), 0 failures
6000: 7770 rt, 4202 ct, 85.997 MB (67.961 increase), 0 failures
7000: 8090 rt, 4316 ct, 85.791 MB (67.755 increase), 0 failures
8000: 8390 rt, 4428 ct, 86.706 MB (68.670 increase), 0 failures
9000: 8690 rt, 4537 ct, 87.416 MB (69.379 increase), 0 failures
10000: 9000 rt, 4647 ct, 86.727 MB (68.691 increase), 0 failures
11000: 9310 rt, 4758 ct, 78.090 MB (60.054 increase), 0 failures
12000: 9620 rt, 4870 ct, 78.401 MB (60.365 increase), 0 failures
13000: 9920 rt, 4983 ct, 81.237 MB (63.200 increase), 0 failures
14000: 10230 rt, 5099 ct, 82.528 MB (64.492 increase), 0 failures
15000: 10540 rt, 5213 ct, 85.618 MB (67.582 increase), 0 failures
16000: 10850 rt, 5340 ct, 87.981 MB (69.944 increase), 0 failures
17000: 11150 rt, 5451 ct, 87.937 MB (69.901 increase), 0 failures
18000: 11470 rt, 5567 ct, 89.678 MB (71.642 increase), 0 failures
19000: 11770 rt, 5682 ct, 88.037 MB (70.000 increase), 0 failures
20000: 12080 rt, 5795 ct, 86.843 MB (68.806 increase), 0 failures
21000: 12390 rt, 5911 ct, 81.511 MB (63.475 increase), 0 failures
22000: 12700 rt, 6022 ct, 76.279 MB (58.243 increase), 0 failures
23000: 13000 rt, 6133 ct, 76.028 MB (57.992 increase), 0 failures
24000: 13340 rt, 6261 ct, 76.415 MB (58.379 increase), 0 failures
25000: 13660 rt, 6375 ct, 78.302 MB (60.266 increase), 0 failures
26000: 13960 rt, 6484 ct, 78.912 MB (60.876 increase), 0 failures
27000: 14250 rt, 6592 ct, 78.747 MB (60.711 increase), 0 failures
28000: 14560 rt, 6710 ct, 78.364 MB (60.328 increase), 0 failures
29000: 14870 rt, 6825 ct, 78.853 MB (60.817 increase), 0 failures
30000: 15180 rt, 6943 ct, 78.871 MB (60.835 increase), 0 failures
31000: 15480 rt, 7058 ct, 80.403 MB (62.367 increase), 0 failures
32000: 15780 rt, 7169 ct, 79.854 MB (61.818 increase), 0 failures
33000: 16080 rt, 7281 ct, 80.761 MB (62.725 increase), 0 failures
34000: 16400 rt, 7399 ct, 79.960 MB (61.924 increase), 0 failures
35000: 16720 rt, 7518 ct, 79.963 MB (61.927 increase), 0 failures
36000: 17020 rt, 7626 ct, 81.016 MB (62.980 increase), 0 failures
37000: 17330 rt, 7747 ct, 80.269 MB (62.233 increase), 0 failures
38000: 17650 rt, 7853 ct, 80.284 MB (62.247 increase), 0 failures
39000: 17960 rt, 7971 ct, 80.638 MB (62.602 increase), 0 failures
40000: 18280 rt, 8091 ct, 80.222 MB (62.186 increase), 0 failures
41000: 18580 rt, 8203 ct, 80.422 MB (62.386 increase), 0 failures
42000: 18880 rt, 8313 ct, 80.571 MB (62.534 increase), 0 failures
43000: 19180 rt, 8428 ct, 80.275 MB (62.239 increase), 0 failures
44000: 19490 rt, 8540 ct, 80.428 MB (62.392 increase), 0 failures
45000: 19800 rt, 8654 ct, 80.602 MB (62.566 increase), 0 failures
46000: 20100 rt, 8766 ct, 81.098 MB (63.062 increase), 0 failures
47000: 20410 rt, 8880 ct, 80.077 MB (62.041 increase), 0 failures
48000: 20720 rt, 9002 ct, 80.163 MB (62.127 increase), 0 failures
49000: 21030 rt, 9122 ct, 80.094 MB (62.058 increase), 0 failures
50000: 21340 rt, 9233 ct, 80.221 MB (62.185 increase), 0 failures
51000: 21650 rt, 9354 ct, 79.771 MB (61.735 increase), 0 failures
52000: 21950 rt, 9470 ct, 81.365 MB (63.328 increase), 0 failures
53000: 22250 rt, 9579 ct, 80.638 MB (62.602 increase), 0 failures
54000: 22550 rt, 9686 ct, 80.507 MB (62.471 increase), 0 failures
55000: 22870 rt, 9811 ct, 80.469 MB (62.433 increase), 0 failures
56000: 23170 rt, 9923 ct, 80.852 MB (62.816 increase), 0 failures
57000: 23490 rt, 10035 ct, 80.361 MB (62.325 increase), 0 failures
58000: 23800 rt, 10147 ct, 80.017 MB (61.981 increase), 0 failures
59000: 24100 rt, 10257 ct, 80.910 MB (62.874 increase), 0 failures
60000: 24410 rt, 10369 ct, 80.355 MB (62.319 increase), 0 failures
61000: 24700 rt, 10478 ct, 79.912 MB (61.876 increase), 0 failures
62000: 25010 rt, 10591 ct, 80.200 MB (62.163 increase), 0 failures
63000: 25320 rt, 10706 ct, 80.060 MB (62.024 increase), 0 failures
64000: 25630 rt, 10828 ct, 79.739 MB (61.702 increase), 0 failures
65000: 25930 rt, 10940 ct, 79.915 MB (61.878 increase), 0 failures
66000: 26230 rt, 11054 ct, 80.157 MB (62.120 increase), 0 failures
67000: 26530 rt, 11164 ct, 80.042 MB (62.006 increase), 0 failures
68000: 26850 rt, 11282 ct, 80.120 MB (62.083 increase), 0 failures
69000: 27160 rt, 11391 ct, 80.228 MB (62.191 increase), 0 failures
70000: 27460 rt, 11509 ct, 79.224 MB (61.188 increase), 0 failures
71000: 27780 rt, 11626 ct, 79.696 MB (61.660 increase), 0 failures
72000: 28080 rt, 11738 ct, 79.701 MB (61.665 increase), 0 failures
73000: 28380 rt, 11853 ct, 80.159 MB (62.122 increase), 0 failures
74000: 28690 rt, 11968 ct, 80.222 MB (62.186 increase), 0 failures
75000: 29000 rt, 12079 ct, 80.496 MB (62.460 increase), 0 failures
76000: 29310 rt, 12199 ct, 79.949 MB (61.913 increase), 0 failures
77000: 29630 rt, 12311 ct, 79.768 MB (61.732 increase), 0 failures
78000: 29940 rt, 12427 ct, 79.429 MB (61.392 increase), 0 failures
79000: 30250 rt, 12545 ct, 79.626 MB (61.589 increase), 0 failures
80000: 30570 rt, 12679 ct, 80.266 MB (62.230 increase), 0 failures
81000: 30880 rt, 12794 ct, 80.890 MB (62.854 increase), 0 failures
82000: 31180 rt, 12903 ct, 79.729 MB (61.693 increase), 0 failures
83000: 31480 rt, 13016 ct, 79.750 MB (61.714 increase), 0 failures
84000: 31780 rt, 13125 ct, 81.310 MB (63.274 increase), 0 failures
85000: 32100 rt, 13241 ct, 79.404 MB (61.368 increase), 0 failures
86000: 32420 rt, 13359 ct, 79.701 MB (61.664 increase), 0 failures
87000: 32730 rt, 13474 ct, 80.223 MB (62.187 increase), 0 failures
88000: 33050 rt, 13594 ct, 80.051 MB (62.015 increase), 0 failures
89000: 33360 rt, 13707 ct, 79.645 MB (61.609 increase), 0 failures
90000: 33670 rt, 13823 ct, 79.563 MB (61.527 increase), 0 failures
91000: 33990 rt, 13943 ct, 79.364 MB (61.328 increase), 0 failures
92000: 34290 rt, 14051 ct, 79.994 MB (61.958 increase), 0 failures
93000: 34610 rt, 14163 ct, 80.217 MB (62.181 increase), 0 failures
94000: 34930 rt, 14280 ct, 80.092 MB (62.056 increase), 0 failures
95000: 35240 rt, 14393 ct, 80.093 MB (62.056 increase), 0 failures
96000: 35570 rt, 14508 ct, 80.090 MB (62.053 increase), 0 failures
97000: 35890 rt, 14626 ct, 79.673 MB (61.637 increase), 0 failures
98000: 36210 rt, 14743 ct, 80.334 MB (62.298 increase), 0 failures
99000: 36520 rt, 14864 ct, 80.259 MB (62.222 increase), 0 failures
100000: 36860 rt, 14985 ct, 79.882 MB (61.846 increase), 0 failures
```

**Comment by yabrams** [comment]
thank you
I'll post our performance results once we'll finish testing the new release

**Pull request closed without merging**
